runtime: nodejs10

manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /(.*\.(json|ico|js|css))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico|js|css)$

  - url: .*
    static_files: dist/index.html
    secure: always
    redirect_http_response_code: 301
    upload: dist/index.html
  # - url: /(.*)/$
  #   static_files: dist/\1/index.html
  #   upload: dist/.*/index.html
  #   secure: always
  #   redirect_http_response_code: 301
  # - url: /
  #   static_dir: dist
